### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by swayson** [RasaHQ/nlu-hyperopt#11]
Hi, wanted to say thanks to the contributors of this one. Being able to see how to setup rasa for hyperparam tuning in this way very helpful.

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by amn41** [comment]
appreciate that! glad you found it helpful.
